
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				zombie = true
				creeper = true
				skeleton = true
				item = true
				spider = true

			[light_sources.settings.entities.tfc]
				fox = true
				direwolf = true
				rabbit = true
				wolf = true
				boar = true

